name: "Chromium Display 3 Kiosk"
version: "1.0.7"
slug: "chromium_display_3_kiosk"
description: "Affichage Kiosque ultra-performant et léger basé sur Chromium Ozone DRM/KMS pour dalles tactiles et caméras."
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
full_access: true
host_ipc: true
udev: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
host_network: true
devices:
  - /dev/dri:/dev/dri
  - /dev/fb0:/dev/fb0
  - /dev/tty0:/dev/tty0
  - /dev/input:/dev/input:rwm
options:
  url: "http://homeassistant:8123/lovelace/0"
schema:
  url: str
